### ISSUE TITLE
Calendar(don't resolve. for Julian and Katrina only)

### ISSUE THREAD

**Issue by katrinaezis** [jamesl5/finalproject#1]
http://bl.ocks.org/mbostock/4063318

**Comment by katrinaezis** [comment]
"streak tracker"

**Comment by jamesl5** [comment]
that looks cool. we gonna use that?

**Comment by jbossiere** [comment]
We're gonna try, haha 

iPhone$B$+$iAw?.(B

2015/11/30 19:44$B!"(Bjamesl5 notifications@github.com $B$N%a%C%;!<%8(B:
